# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-27 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='text',
            field=models.CharField(default='Inro text', max_length=250),
        ),
    ]
