# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-27 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='description',
            field=models.CharField(default='', max_length=250),
        ),
    ]
