# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-27 22:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepage_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='CenterMessage_description',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='homepage',
            name='CenterMessage_header',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='homepage',
            name='Footer_header',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='homepage',
            name='btn_name',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='homepage',
            name='contact_us',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='homepage',
            name='contact_us_text',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='homepage',
            name='footer_text',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='homepage',
            name='more_information',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='homepage',
            name='more_information_text',
            field=models.CharField(default='', max_length=250),
        ),
    ]
