# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-27 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20171227_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='CenterMessage_description',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
