# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-28 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20171228_1315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='CenterMessage_header',
            new_name='Center_Message_header',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='CenterMessage_description',
        ),
        migrations.AddField(
            model_name='homepage',
            name='Center_Message_description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='homepage',
            name='contact_us_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='more_information_text',
            field=models.TextField(),
        ),
    ]
